// The Procedures page rendered EVERY step of EVERY recipe: measured on the real database,
// 92 recipes / 1,121 steps / 24,202 elements / 1,690 KB. One recipe alone (indeed) held 532
// steps -- a scroll nobody has ever reached the bottom of, paid for on every single visit.
//
// The fix caps each recipe at its first 20 steps and offers the rest behind one button.
// Measured after: 10,051 elements / 683 KB, with all 92 recipe cards still present.
//
// THE TRAP THIS FILE EXISTS TO GUARD is not the cap -- it is the binding. The old code bound
// every control with a single `v.querySelectorAll('.proc-step').forEach(...)` at render time.
// Steps revealed later were never in that NodeList, so their buttons would look completely
// normal and do NOTHING. That is the same silent failure the Applications and Profile tables
// each shipped with, and it is invisible to the eye: a dead button and a live button are
// pixel-identical.
import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const here = path.dirname(fileURLToPath(import.meta.url));
const APP = fs.readFileSync(path.join(here, '..', 'extension', 'app', 'app.js'), 'utf8');
const MIRROR = fs.readFileSync(path.join(here, '..', 'app', 'src', 'app', 'app.js'), 'utf8');

test('the authored file and its mirror agree', () => {
  // extension/app is AUTHORED; app/src/app is generated by tools/mirror.mjs. A fix applied to
  // only one of them ships to only one of the two places the dashboard is served from.
  assert.equal(APP, MIRROR, 'run `node tools/mirror.mjs` — the two copies have diverged');
});

test('steps are capped per recipe, not page-wide', () => {
  // Page-wide would be wrong: it would truncate the 91 small recipes to make room for indeed.
  // The cap belongs inside the per-recipe renderer.
  const i = APP.indexOf('const recipeCardHtml =');
  assert.ok(i > 0, 'the recipe renderer must still exist');
  const fn = APP.slice(i, i + 2000);
  assert.match(fn, /const STEP_CAP = 20;/, 'the cap must live inside recipeCardHtml');
  assert.match(fn, /steps\.slice\(0, STEP_CAP\)/, 'and be applied to that recipe\'s own steps');
});

test('every recipe still renders — the cap hides steps, never a recipe', () => {
  const i = APP.indexOf('const recipeCardHtml =');
  const fn = APP.slice(i, i + 2000);
  assert.ok(!/recipes\.slice\(/.test(fn), 'recipes themselves must never be truncated');
});

test('THE BUG: binding is a function called again after a reveal, not a one-shot at render', () => {
  // If this reverts to a bare `v.querySelectorAll('.proc-step').forEach(...)` with no re-bind,
  // every revealed step goes dead silently.
  assert.match(APP, /const bindStep = \(row\) => \{/,
    'binding one step must be a named, re-callable function');
  assert.match(APP, /const bindAllSteps = \(\) =>/,
    'and there must be a bind-anything-not-yet-bound sweep');
  const reveal = APP.slice(APP.indexOf('data-proc-more]'), APP.indexOf('data-proc-more]') + 900);
  assert.match(reveal, /bindAllSteps\(\)/,
    'the reveal handler MUST re-bind, or the 512 steps it inserts are dead controls');
});

test('re-binding is idempotent — a step must not collect a second listener', () => {
  // bindAllSteps() runs on render AND after every reveal. Without a guard, a step present at
  // render would get a second click handler and every action would fire twice: two PATCHes,
  // two reorders, two deletes.
  assert.match(APP, /if \(row\.dataset\.stepBound\) return;/,
    'an already-bound row must be skipped');
  assert.match(APP, /row\.dataset\.stepBound = '1';/, 'and marked when bound');
});

test('the reveal button announces the real remaining count', () => {
  assert.match(APP, /Show the other \$\{steps\.length - STEP_CAP\} steps/,
    'a vague "show more" hides how much is behind it; on indeed the honest number is 512');
});

test('the reveal renders through the SAME row builder as the initial paint', () => {
  // Two builders would drift, and the revealed rows would slowly stop matching the visible ones.
  const reveal = APP.slice(APP.indexOf('data-proc-more]'), APP.indexOf('data-proc-more]') + 900);
  assert.match(reveal, /stepRowHtml\(recipe, s, i \+ 20, all\.length\)/,
    'revealed steps must use stepRowHtml with their TRUE index, so ↑/↓ reorder correctly');
});

// ---------------------------------------------------------------------------------------
// Verified in a real browser against a copy of the live database before this was committed:
//
//   * 24,202 -> 10,051 elements, 1,690 -> 683 KB, all 92 recipe cards present, 0 console errors
//   * "Show the other 512 steps" -> 457 -> 969 steps, exactly 512 with data-idx >= 20
//   * clicked ↔ scope on the step at index 270 (which cannot exist without the reveal) and
//     confirmed THE SERVER changed, then restored it
//
// That last check nearly recorded a false failure. A scope flip does NOT write a `scope` column
// on the step -- updateRecipeStepFields MOVES the step into the recipe's sibling of the other
// scope, changing recipe_id. Reading `step.scope` showed null both before and after and looked
// exactly like a dead button. The control that proves the click landed is which recipe now
// owns the step, which is what this test pins.
test('a scope flip is a MOVE between recipes, not a field write', () => {
  const i = APP.indexOf('const patchStep = async');
  assert.ok(i > 0);
  const flip = APP.slice(APP.indexOf("[data-flip-scope]"), APP.indexOf("[data-flip-scope]") + 400);
  assert.match(flip, /patchStep\(stepId, \{ scope: scope === 'company' \? 'ats' : 'company' \}/,
    'the flip sends the OPPOSITE scope; the server resolves it into a recipe move');
});
